version: '3'
services:
  php:
    container_name: php
    image: php:fpm-alpine
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../:/var/www/html:rw
    networks:
      - internal
      
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html:rw
      - ./default.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - php
    networks:
      - internal

networks:
  internal:
